"""Init

Revision ID: 2db37ccba0b4
Revises: 
Create Date: 2026-04-12 18:30:38.163767

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '2db37ccba0b4'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('books',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('name', sa.VARCHAR(length=255), nullable=False),
    sa.Column('author', sa.VARCHAR(length=255), nullable=False),
    sa.Column('year', sa.VARCHAR(length=4), nullable=False),
    sa.Column('cost', sa.DECIMAL(precision=10, scale=2), nullable=False),
    sa.Column('tags', sa.JSON(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('offices',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('adrres', sa.VARCHAR(length=255), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('users',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('firs_name', sa.VARCHAR(length=255), nullable=False),
    sa.Column('last_name', sa.VARCHAR(length=255), nullable=False),
    sa.Column('create_at', sa.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('is_admin', sa.Boolean(), server_default='False', nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('cabinets',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('name', sa.VARCHAR(length=255), nullable=False),
    sa.Column('owner_id', sa.BigInteger(), nullable=False),
    sa.Column('office_id', sa.BigInteger(), nullable=False),
    sa.Column('number', sa.VARCHAR(length=10), nullable=False),
    sa.ForeignKeyConstraint(['office_id'], ['offices.id'], ),
    sa.ForeignKeyConstraint(['owner_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('user_books',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('book_id', sa.BigInteger(), nullable=False),
    sa.Column('user_id', sa.BigInteger(), nullable=False),
    sa.Column('borrowed_at', sa.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('returned_at', sa.TIMESTAMP(timezone=True), nullable=True),
    sa.Column('is_returned', sa.Boolean(), server_default='False', nullable=False),
    sa.ForeignKeyConstraint(['book_id'], ['books.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('book_cabinets',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('book_id', sa.BigInteger(), nullable=False),
    sa.Column('cabinet_id', sa.BigInteger(), nullable=False),
    sa.Column('is_exist', sa.Boolean(), server_default='True', nullable=False),
    sa.Column('create_at', sa.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('update_at', sa.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['book_id'], ['books.id'], ),
    sa.ForeignKeyConstraint(['cabinet_id'], ['cabinets.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('book_cabinets')
    op.drop_table('user_books')
    op.drop_table('cabinets')
    op.drop_table('users')
    op.drop_table('offices')
    op.drop_table('books')
    # ### end Alembic commands ###
